<<<<<<< HEAD
title: ChenSiYu
description: "chensiyu's blog"
author:
  name: "chensiyu"
  email: "sy.chen@live.it"
  url: "https:chensiyu.co"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "chensiyu"
year : "2018"
=======
permalink: /:year:month:day/:title
url: https://chensiyu.co

# variables
name: chensiyu.io
description: 
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass
>>>>>>> fba0527f1f5f33198348e503ce56a98b70fa745d
